export const initialShippings = [
  {
    id: 1566315984000,
    date: new Date("January 30, 2018 012:29:00"),
    fromName: "German Cardenas",
    fromStreet: "Calle 27 sur # 27B - 87",
    fromZipCode: "055420",
    fromCity: "New York",
    fromState: "NY",
    toName: "Paola Montes",
    toStreet: "Carrera 77 sur # 27B - 87",
    toZipCode: "033212",
    toCity: "Atlanta",
    toState: "GA",
    deliveryMethod: "regular",
    price: "127",
    status: "delivered",
    qty: 2
  },
  {
    id: 1576316984000,
    date: new Date("December 17, 2018 03:24:00"),
    fromName: "German Cardenas",
    fromStreet: "Calle 27 sur # 27B - 87",
    fromZipCode: "055420",
    fromCity: "New York",
    fromState: "NY",
    toName: "Paola Montes",
    toStreet: "Carrera 77 sur # 27B - 87",
    toZipCode: "033212",
    toCity: "Atlanta",
    toState: "GA",
    deliveryMethod: "regular",
    price: "230",
    status: "transit",
    qty: 1
  },
  {
    id: 1566314984000,
    date: new Date("November 05, 2018 8:07:00"),
    fromName: "German Cardenas",
    fromStreet: "Calle 27 sur # 27B - 87",
    fromZipCode: "055420",
    fromCity: "New York",
    fromState: "NY",
    toName: "Paola Montes",
    toStreet: "Carrera 77 sur # 27B - 87",
    toZipCode: "033212",
    toCity: "Atlanta",
    toState: "GA",
    deliveryMethod: "regular",
    price: "573",
    status: "delayed",
    qty: 5
  }
];

export const initialShippingFormState = {
  id: "",
  date: "",
  fromName: "German",
  fromStreet: "",
  fromZipCode: "",
  fromCity: "",
  fromState: "",
  toName: "Paolaa",
  toStreet: "",
  toZipCode: "",
  toCity: "",
  toState: "",
  deliveryMethod: "regular",
  price: "",
  status: "delayed",
  qty: 3
};
